@host=https://localhost:7210

POST {{host}}/auth/register
Content-Type: application/json

{
    "username": "John",
    "email": "test@email.com",
    "password": "testPassword",
    "confirmPassword": "testPassword",
    "firstName": "Alex",
    "lastName": "Smith",
    "status": "student"
}