POST https://localhost:7210/auth/register
Content-Type: application/json

{
    "username": "Ilya_3004",
    "email": "ilya@gmail.com",
    "password": "ilya_3004",
    "confirmPassword": "ilya_3004",
    "firstName": "Ilya",
    "lastName": "Melnichuk",
    "status": "student"
}